<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testEMF" nsURI="http://www.example.org/testEMF" nsPrefix="testEMF">
  <eClassifiers xsi:type="ecore:EClass" name="Truc">
    <eOperations name="affiche" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="ch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chose" eType="#//Chose"
        eOpposite="#//Chose/trucs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chose">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trucs" upperBound="-1"
        eType="#//Truc" eOpposite="#//Truc/chose"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chose" upperBound="-1"
        eType="#//Chose" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="truc" upperBound="-1" eType="#//Truc"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
